### ISSUE TITLE
KBS Operator

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/confidential-containers#106]
## Project Description

KBS is a critical part of the CoCo stack and it'll help to have a K8s operator to deploy and manage KBS.
We already have Kubernetes [manifest](https://github.com/confidential-containers/kbs/tree/main/config/kubernetes) to deploy KBS. The next evolution to help with managing the lifecycle of KBS is to create a K8s operator. 

Ref: https://github.com/confidential-containers/kbs/issues/119

## Alignment with Confidential Containers

Since KBS is part of the CoCo project, it makes sense to have kbs operator under the same project

## GitHub repositories needed

I think `kbs-operator` may be ok. Please feel free to suggest any alternatives.

**Comment by bpradipt** [comment]
Here is the initial working code with basic functionality - https://github.com/bpradipt/kbs-operator

**Comment by Xynnn007** [comment]
Wow. Thanks @bpradipt  It looks COOL to me!

**Comment by fitzthum** [comment]
Nice. Let's try to get this project going. One question: would it make any sense to put this in the existing KBS repo or is this more generic?

**Comment by bpradipt** [comment]
> Nice. Let's try to get this project going. One question: would it make any sense to put this in the existing KBS repo or is this more generic?

@fitzthum are you suggesting a folder in the kbs project ? If yes, then technically it should work. But having a separate repo makes it easy for setting up CI and other automation workflows in my experience. 

@jensfr @surajssd any suggestions from your side ?

**Comment by sameo** [comment]
After the coco meeting discussion, I am +1 on that. We can go ahead and create it unless someone raises a strong objection.

**Comment by fidencio** [comment]
+1 as well, mainly for going on its own repo.

**Comment by fitzthum** [comment]
Ok, lgtm. A separate repo seems fine.

**Comment by surajssd** [comment]
I think there are more pros to having operator and the main KBS code in the same repository, especially around overall project delivery.

To me operator is just another method of installing a software on Kubernetes similar to the plain simple YAML configuration.

Pros of single repository:

- Having it in the same repository means we can do end to end tests on each code change of the main application. Hence the operator and the main application both code paths are tested. With different repositories we will test only the deployment code and the KBS repo might suggest a different deployment model. This proliferation of deployment models confuses users.

- Issues regarding the main app and its deployment method (operator) stay in the same repository. Thus if there is a new feature in the KBS app and that needs change in the deployment method, the issues can be tracked.

---

I would also like to know the need for an operator in KBS's case? As I have asked here: https://github.com/confidential-containers/kbs/issues/119#issuecomment-1624429252

**Comment by jensfr** [comment]
I'd prefer to have kbs-operator in its own repo. IMHO there's many reasons already mentioned by others. Most import to me is that it's easier to follow changes. Also I see it as it's own (sub)-project, it's not tightly coupled to something else. +1 for a separate repo from me

**Comment by bpradipt** [comment]
@surajssd as we discussed in the community call on 6th of July, both the options have their merits. And what you mentioned makes sense.
However I'll tend to align towards having a separate repo primarily for the following reasons:

- Easier release management and automation handling 
- Handling of vulnerabilities, CVEs etc (part of release management)
- Importing the operator controller as a go module is easier when using a separate repo
- Loosely coupled with kbs repo to have flexibility w.r.to release cadence, policies, maintainers, reviewer, committers etc

For now I'll go ahead with a separate repo and raise the PR to move ahead.

If going forward we feel that having a separate repo is more of a pain then we can add it as a folder. Nothing is written in stone.

**Comment by larrydewey** [comment]
cc @ryansavino @UnmeshDeodhar

**Comment by fitzthum** [comment]
New repo has been made. We can always consolidate later if this turns out to be a mistake.
