### ISSUE TITLE
[Release] Check list for v0.7.0

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/confidential-containers#111]
# v0.7.0

## Code freeze

~- [ ] 1. Update image-rs to use the latest commit from ocicrypt-rs~
        
    * https://github.com/confidential-containers/image-rs/blob/main/Cargo.toml
      * Change the revision
      * Run `cargo update -p ocicrypt-rs`

~- [ ] 2. Update image-rs to use the latest commit from attestation-agent~

    * https://github.com/confidential-containers/image-rs/blob/main/Cargo.toml
      * Change the revision
      * Run `cargo update -p attestation_agent`

- [x] 3. Update Enclave CC to use the latest commit from image-rs
     PR: https://github.com/confidential-containers/enclave-cc/pull/188
    * https://github.com/confidential-containers/enclave-cc/blob/main/src/enclave-agent/Cargo.toml
      * Change the revision
      * Run `cargo update -p image-rs`
        Note that you can point to your own fork here, so you don't actually do changes in the other projects
        before making sure this step works as expected.

- [x] 4. Update Kata Containers to use the latest commit from image-rs, attestation-agent and td-shim
    PR: https://github.com/kata-containers/kata-containers/pull/7354
    * image-rs
      * https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/Cargo.toml
      * Change the revision
      * Run `cargo update -p image-rs`
          Note that you can point to your own fork here, so you don't actually do changes in the other projects
          before making sure this step works as expected.
    * attestation-agent and td-shim
      * https://github.com/kata-containers/kata-containers/blob/CCv0/versions.yaml
        * Change the version

- [x] 5. Wait for kata-runtime-payload-ci to be successfully built
    * After the previous PR is merged wait for the kata-runtime-payload-ci (https://github.com/kata-containers/kata-containers/actions/workflows/cc-payload-after-push.yaml) has completed, so the latest kata-runtime-payload-ci contains the changes

- [x] 6. Check if there are new changes in the pre install payload script (@wainersm is going to work on that)

    * https://github.com/confidential-containers/operator/tree/main/install/pre-install-payload
      * The last commit there must match what's in the following files as preInstall / postUninstall image
        * Enclave CC: https://github.com/confidential-containers/operator/blob/main/config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
        * Kata Containers:
              Note that for Kata Containers, we're looking for the newTag, below the quay.io/confidential-containers/container-engine-for-cc-payload image
          * default: https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/default/kustomization.yaml

- [x] 7. Ensure the Operator is using the latest CI builds and that the Operator tests are passing
    PR: https://github.com/confidential-containers/operator/pull/228

    * Enclave CC:
      * SIM: https://github.com/confidential-containers/operator/blob/main/config/samples/enclave-cc/sim/kustomization.yaml
      * HW: https://github.com/confidential-containers/operator/blob/main/config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
      * Note that we need the quay.io/confidential-containers/runtime-payload-ci registry and enclave-cc-{SIM,HW}-latest tags
    * Kata Containers:
      * default: https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/default/kustomization.yaml
      * peer-pods: https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/peer-pods/kustomization.yaml
          Note that we need the quay.io/confidential-containers/runtime-payload-ci registry and kata-containers-latest tag

- [x] 8. Update peer-pods with latest commits of kata-containers and attestation-agent and test it, following the [release candidate testing process](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/docs/Release-Process.md#release-candidate-testing)
    
~- [ ] 9. Cut an ocicrypt-rs v0.7.0 release, if changes happened in the project~

~- [ ] 10. Cut an attestation-agent v0.7.0, if changes happened in the project~

- [x] 11. Cut an attestation-service v0.7.0 and make images for AS and RVPS, if changes happened in the project.
       Release: https://github.com/confidential-containers/attestation-service/releases/tag/v0.7.0
       * https://github.com/confidential-containers/attestation-service
       * Cut a release (AS/RVPS images will be automatically built triggered by release)

- [x] 12. Update kbs to use the latest commit from attestation-service, cut a release and make image
       PR: https://github.com/confidential-containers/kbs/pull/132
       * https://github.com/confidential-containers/kbs/blob/main/src/api_server/Cargo.toml
       * Change the revision for the following crates (both use `v0.7.0`)
     * `as-types`
     * `attestation-service`
       * Cut a release (kbs image will be automatically built triggered by release)

~- [ ] 13. Cut an image-rs v0.7.0 release, using the latest release of:~

    * ocicrypt-rs (redo step 1, but now using v0.7.0)
    * attestation-agent (redo step 2, but now using v0.7.0)

- [x] 14. Cut a td-shim v0.7.0 release, if changes happened in the project

- [x] 15. Update Enclave CC to use the released version of image-rs
    PR: https://github.com/confidential-containers/enclave-cc/pull/190
    * redo step 3, but now using v0.7.0

- [x] 16. Update Kata Containers to the latest released version of:
    PR: https://github.com/kata-containers/kata-containers/pull/7401
    * image-rs (redo step 4, but now using the v0.7.0)
    * attestation-agent (redo step 5, but now using the v0.7.0)
    * td-shim (redo step 6, but now using the v0.7.0)

- [x] 17. Update the operator to use the images generated from the latest commit of both Kata Containers and Enclave CC
    PR: https://github.com/confidential-containers/operator/pull/232
    * redo step 8, but now targetting the latest payload image generated for Kata Containers and Enclave CC

- [x] 18. Make sure all the operator tests are passing

- [x] 19. Cut an Enclave CC release

- [x] 20. Add a new Kata Containers tag

- [x] 21. Wait for release kata-runtime-payload to be successfully built
    * After the Kata tag is created wait for (https://github.com/kata-containers/kata-containers/actions/workflows/cc-payload.yaml) to be successfully completed, so the latest commit kata-runtime-payload for the release is created

- [x] 22. Update peer pods to use the release versions and then cut a release following the [documented flow](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/docs/Release-Process.md#cutting-releases)

## Release

- [x] 23. Update the operator to use the release tags coming from Enclave CC and Kata Containers
    PR: https://github.com/confidential-containers/operator/pull/233
    * redo step 8, but now targeting the latest release of the payload image generated for Kata Containers eand Enclave CC

- [x] 24. Update the Operator version
    PR: https://github.com/confidential-containers/operator/pull/234
    * https://github.com/confidential-containers/operator/blob/main/config/release/kustomization.yaml#L7

- [x] 25. Cut an operator release
   Release: https://github.com/confidential-containers/operator/releases/tag/v0.7.0

- [x] 26. Make sure to update the release notes
      PR: https://github.com/confidential-containers/confidential-containers/pull/113

    * https://github.com/confidential-containers/documentation/tree/main/releases/v0.7.0.md
        
- [ ] 27. Poke Wainer Moschetta (@wainersm) to update the release to the OperatorHub

**Comment by fitzthum** [comment]
Are the first four steps still necessary?

**Comment by fitzthum** [comment]
Also, do we want to use Steve's PR from yesterday that bumped the guest components version as step 5?

**Comment by wainersm** [comment]
> Are the first four steps still necessary? 

I think that step 1 and 2 are still necessary but in a slightly different way. In CCA we have an alike situation but it is golang: submodules with inter-dependencies, that we release using [this process](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/docs/Release-Process.md#tags-and-update-go-submodules). If the same idea applies to Rust then we should:

a. Create tags for ocicrypt-rs and attestation_agent. Example:
```
 git tag ocicrypt-rs/v<version>-alpha.1 main
 git push origin ocicrypt-rs/v<version>-alpha.1
 git tag attestation_agent/v<version>-alpha.1 main
 git push origin attestation_agent/v<version>-alpha.1
```
b. Update image-rs to use the alpha.1 tagged ocicrypt-rs and attestation-agent (remove the relative path dependencies)

c. Commit an alpha.1 release of guest-components
     
The step 3 changes to use the tagged guest-components.

@confidential-containers/guest-components-maintainers could you please advice? How should we handle the guest-components release?

**Comment by fitzthum** [comment]
Hm I see where you are coming from, but wouldn't that all be functionally equivalent to just having one tag for the entire guest components repo? Having different tags for the different subprojects would allow us to use different versions of the different subprojects, but I thought one of the ideas behind the repo merge was to avoid doing that.

wdyt @Xynnn007 ?

**Comment by Xynnn007** [comment]
> Having different tags for the different subprojects would allow us to use different versions of the different subprojects, but I thought one of the ideas behind the repo merge was to avoid doing that.

Yes. Our first idea is to avoid that in CoCo development. FMOO, we do not need step 1, 2, 9, 10, 13 for now as we still not publish the crates on `crates.io`



> I think that step 1 and 2 are still necessary but in a slightly different way. In CCA we have an alike situation but it is golang: submodules with inter-dependencies, that we release using [this process](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/docs/Release-Process.md#tags-and-update-go-submodules). If the same idea applies to Rust then we should:

I'm not familiar with golang published mods, but I think it is somehow similar to Rust's. This is for the published golang mods to find the dependency online with the mod rev.

But for guest-components now, we have not published the crates on `crates.io` yet. Thus we can still use the `git`+`tag` or `git`+`rev` ways to specify the dep version. That means we can do something like this (I have test this with my own repo):
```toml
ocicrypt-rs = { git = "https://github.com/confidential-containers/guest-components.git", tag = "v0.7.0" }
crypto = { git = "https://github.com/confidential-containers/guest-components.git", tag = "v0.8.0" }
```

In future, when we decide to publish the crates on `crates.io`, where we should change is the `version` field inside the `Cargo.toml`. For example `ocicrypt-rs`'s https://github.com/confidential-containers/guest-components/blob/main/ocicrypt-rs/Cargo.toml#L3 .  We can use a single commit like [what `serde` did](https://github.com/serde-rs/serde/commit/03da66c805499a9e79a5b6cb11fa21ef6da636eb) which include:
- update version number of `ocicrypt-rs`. For example `0.12.0`
- update `ocicrypt-rs = { path = "../ocicrypt-rs", default-features = false, features = ["async-io"], optional = true }` in `image-rs`'s `Cargo.toml` to `ocicrypt-rs = { version = "0.12.0" , default-features = false, features = ["async-io"], optional = true }`

**Comment by wainersm** [comment]
> > Having different tags for the different subprojects would allow us to use different versions of the different subprojects, but I thought one of the ideas behind the repo merge was to avoid doing that.
> 
> Yes. Our first idea is to avoid that in CoCo development. FMOO, we do not need step 1, 2, 9, 10, 13 for now as we still not publish the crates on `crates.io`
>

So I disabled those steps (~straight line~) and opened a PR to update the checklist (https://github.com/confidential-containers/confidential-containers/pull/112).
 
> > I think that step 1 and 2 are still necessary but in a slightly different way. In CCA we have an alike situation but it is golang: submodules with inter-dependencies, that we release using [this process](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/docs/Release-Process.md#tags-and-update-go-submodules). If the same idea applies to Rust then we should:
> 
> I'm not familiar with golang published mods, but I think it is somehow similar to Rust's. This is for the published golang mods to find the dependency online with the mod rev.
> 
> But for guest-components now, we have not published the crates on `crates.io` yet. Thus we can still use the `git`+`tag` or `git`+`rev` ways to specify the dep version. That means we can do something like this (I have test this with my own repo):
> 
> ```toml
> ocicrypt-rs = { git = "https://github.com/confidential-containers/guest-components.git", tag = "v0.7.0" }
> crypto = { git = "https://github.com/confidential-containers/guest-components.git", tag = "v0.8.0" }
> ```
> 
> In future, when we decide to publish the crates on `crates.io`, where we should change is the `version` field inside the `Cargo.toml`. For example `ocicrypt-rs`'s https://github.com/confidential-containers/guest-components/blob/main/ocicrypt-rs/Cargo.toml#L3 . We can use a single commit like [what `serde` did](https://github.com/serde-rs/serde/commit/03da66c805499a9e79a5b6cb11fa21ef6da636eb) which include:
> 
>     * update version number of `ocicrypt-rs`. For example `0.12.0`
> 
>     * update `ocicrypt-rs = { path = "../ocicrypt-rs", default-features = false, features = ["async-io"], optional = true }` in `image-rs`'s `Cargo.toml` to `ocicrypt-rs = { version = "0.12.0" , default-features = false, features = ["async-io"], optional = true }`

Thanks for the explanation @Xynnn007 !

**Comment by jepio** [comment]
37bff8c3c706a60742729539d8e58f8a229ec339 is the guest-components rc.

**Comment by jepio** [comment]
New guest-components rc is 88dcc147ba8ddf34e8425c98d5931df8a995f04a.

**Comment by wainersm** [comment]
Regarding step 6, there is an updated version (https://github.com/confidential-containers/containerd/releases/tag/v1.6.8.2) of [our forked containerd](https://github.com/confidential-containers/containerd) due to https://github.com/kata-containers/kata-containers/pull/7332 . We updated the pre-install build script in https://github.com/confidential-containers/operator/pull/225 and a new pre-install image was built on  https://github.com/confidential-containers/operator/actions/runs/5599697835/jobs/10241012686

The new pre-install image is quay.io/confidential-containers/container-engine-for-cc-payload:c80c3e7392c1562841e75072d227e07f98cab2bd 

We are working to get https://github.com/kata-containers/kata-containers/pull/7332 merged to then open a PR to build the kata-containers payload and pre-install images on the operator.

**Comment by fitzthum** [comment]
Any lingering tasks here or can we closes?

**Comment by wainersm** [comment]
> Any lingering tasks here or can we closes?

step  22 - I cut the release today but I am waiting until tomorrow peer pods folks to report manual tests. With IBM cloud and libvirt all e2e tests passed.

I am still working on step 27. So let's keep this issue open a little longer.

**Comment by surajssd** [comment]
@wainersm can we close this one?
