### ISSUE TITLE
[RFC] Trusted storage proposal for CoCo

### ISSUE THREAD

**Issue by arronwy** [confidential-containers/confidential-containers#123]
## Motivation
The CoCo stack utilizes hardware-based TEE technology for runtime protection which provides the confidential memory. Current CoCo uses confidential memory for data storage like container images, container RW layers. Memory is an expensive resource and we need a low cost solution to provide trusted storage as part of CoCo stack. Thanks @jiangliu and @liangzhou121, this proposal is based on https://github.com/confidential-containers/documentation/pull/23 and https://github.com/confidential-containers/documentation/issues/20 .

## Short Term Goals
* Provide Confidential Ephemeral Storage
    1. Auto crypt setup(encrypt) for the storage, use `dm-crypt` to protect the block volume
    2. Use `dm-integrity` to protect the integrity of encrypted block volume
    3. Host downloaded container images (Pod level)
    4. Host RW layer of container rootfs
    5. Provide ephemeral volume for containers 
* Compatible with current Kubernetes PodSpec
    1. Use `pause` sidecar container to host the block volume
* Integrate with at least one Kubernetes CSI driver
    1. open-local: https://github.com/alibaba/open-local
    2. topolvm: https://github.com/topolvm/topolvm

## Long Term Goals
* Provide Confidential Persistent Storage
    1. Auto crypt setup(encrypt/decrypt) for the storage
    2. Use `dm-integrity` to protect the integrity of encrypted block volume
* Transparent for the pod spec of enduser
   1. Utilize Kubernetes MutatingAdmissionWebhook to auto inject the config
* Kubernetes support Pod level storage resource definition and allocation

## High Level Architecture
![image](https://user-images.githubusercontent.com/13145624/176380524-f7afc9e4-9ccf-4dd5-b1e9-9ff83a493e5d.png)
This is the high level architecture for trusted storage for CoCo. The CSI driver will dynamically provision and allocate a block volume for the pod. We will associate this block volume with a sidecar container with `pause` image. Since the block volume will be used to store container images, to avoid the bootstrap issue, the `pause` image will be in the rootfs by default to avoid image downloading. After the block volume is attached to guest through virtio-blk, the kata-agent will do the initialization and crypt setup work, if the block device is encrypted, kata-agent will get the decrypt key from trusted party like attestation-agent.

## Implementation Details
* PodSpec Definition
Since the volumes consumed by a pod need associate with one container, we choose use a sidecar container with `pause` image to host the block volume:
![image](https://user-images.githubusercontent.com/13145624/176388526-419f5e5c-1b1f-4528-b5c7-270c109e68eb.png)

```
apiVersion: v1
kind: Pod
metadata:
  name: trusted-lvm-block
spec:
  runtimeClassName: kata-cc
  containers:
   - name: sidecar-trusted-store
     image: pause
     volumeDevices:
     - devicePath: "/dev/trusted_store"
       name: trusted-store

  volumes:
   - name: trusted-store
     persistentVolumeClaim:
       claimName: trusted-store-block-pvc
```
* Kata Guest Kernel
Add dm-crypt/integrity required kernel config
* Kata rootfs
Add `pause` image, cryptsetup and filesystem utilities related packages into the rootfs
* Kata-agent
Detect the block volume with device path: `/dev/trusted_store`, start the crypt setup and file system initialization for this volume and mount the encrypted disk to the container image store path: `/run/image`. The following containers images and container RW layers will saved in this directory.

This is the demo link:
https://asciinema.org/a/W90GYRZmFoCb1nEIKS3BjAToH

## Potential GAPs
* Container launch sequence
The `initContainer` will launch sequencely and will wait previous container finished successfully, but normal container for `runc` runtime will launch in paralle, but for `kata` runtime I found they also run sequencely, but we need define the sidecar container before normal application container.

* Storage resouce restriction for each container
After kata-agent setup the block volume and export as directory for other containers to use, currently there don't have resource restriction for each container

* Container defined mount path support
In pod yaml file, the volumes can be used as shared volume to allow the communication between containers, after kata-agent manage the block volume, the definition for each containers to define the mount path also need support.

* Block volume sharing between pods
Since the volume is encrypted and can not mount by other pods, sharing between pods is not supported

## Devel Plan for CoCo first release
For CoCo September first release, we will support the ephemeral trusted storage to host container images and RW layers.
* [x] Guest kernel support dm-integrity, dm-crypt
* [x] Integrate cryptsetup and filesystem utilities into Kata rootfs
* [x] Package `pause` image inside Kata rootfs
* [x] Kata agent crypt setup raw block volume with shell scripts
* [ ] Kata agent crypt setup raw block volume with rust native implementation(one GAP is `libcryptsetup-rs` don't support musl build)
* [x] Mount the encrypted disk for image/container RW layer store

The next step will be support the persistent trusted storage with Kata direct volume features.
* [ ] Kata agent retrive disk encrypted key from `attestation-agent`
* [ ] Kata agent crypt setup persistent encrypted raw block vloume

**Comment by Villain88** [comment]
Hello. Is there any possibility to share pvc between containers within a single pod in the current version? If I understand correctly, now each container has its own layer (/run/image/overlay/<id>/upperdir) and the data is isolated?

**Comment by arronwy** [comment]
We can close this issue now:
Trusted Ephemeral Storage for container images: https://github.com/confidential-containers/confidential-containers/blob/main/guides/ephemeral_storage.md
Trusted persistent storage: https://github.com/confidential-containers/guest-components/blob/main/confidential-data-hub/docs/SECURE_STORAGE.md
