### ISSUE TITLE
[Release] Check list for v0.8.0

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/confidential-containers#145]
# v0.8.0

## Code freeze

- [x] 1. Update Enclave CC to use the latest commit from image-rs
    PR: https://github.com/confidential-containers/enclave-cc/pull/263
https://github.com/confidential-containers/enclave-cc/pull/268
    * https://github.com/confidential-containers/enclave-cc/blob/main/src/enclave-agent/Cargo.toml
      * Change the revision
      * Run `cargo update -p image-rs`
        Note that you can point to your own fork here, so you don't actually do changes in the other projects
        before making sure this step works as expected.

- [x] 2. Update Kata Containers to use the latest commit from image-rs, attestation-agent and td-shim
    PR: https://github.com/kata-containers/kata-containers/pull/7852
    * image-rs
      * https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/Cargo.toml
      * Change the revision
      * Run `cargo update -p image-rs`
          Note that you can point to your own fork here, so you don't actually do changes in the other projects
          before making sure this step works as expected.
    * attestation-agent and td-shim
      * https://github.com/kata-containers/kata-containers/blob/CCv0/versions.yaml
        * Change the version

- [x] 3. Wait for kata-runtime-payload-ci to be successfully built
    * After the previous PR is merged wait for the kata-runtime-payload-ci (https://github.com/kata-containers/kata-containers/actions/workflows/cc-payload-after-push.yaml) has completed, so the latest kata-runtime-payload-ci contains the changes

- [x] 4. Check if there are new changes in the pre install payload script

    * https://github.com/confidential-containers/operator/tree/main/install/pre-install-payload
      * The last commit there must match what's in the following files as preInstall / postUninstall image
        * Enclave CC: https://github.com/confidential-containers/operator/blob/main/config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
        * Kata Containers:
              Note that for Kata Containers, we're looking for the newTag, below the quay.io/confidential-containers/container-engine-for-cc-payload image
          * default: https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/default/kustomization.yaml

- [x] 5. Ensure the Operator is using the latest CI builds and that the Operator tests are passsing
   PR: https://github.com/confidential-containers/operator/pull/277
    * Enclave CC:
      * SIM: https://github.com/confidential-containers/operator/blob/main/config/samples/enclave-cc/sim/kustomization.yaml
      * HW: https://github.com/confidential-containers/operator/blob/main/config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
      * Note that we need the quay.io/confidential-containers/runtime-payload-ci registry and enclave-cc-{SIM,HW}-latest tags
    * Kata Containers:
      * default: https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/default/kustomization.yaml
      * peer-pods: https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/peer-pods/kustomization.yaml
          Note that we need the quay.io/confidential-containers/runtime-payload-ci registry and kata-containers-latest tag

- [ ] 6. Update peer-pods with latest commits of kata-containers and attestation-agent and test it, following the [release candidate testing process](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/docs/Release-Process.md#release-candidate-testing)
    
- [x] 7. Cut an attestation-service v0.8.0 and make images for AS and RVPS, if changes happened in the project.
       Release: https://github.com/confidential-containers/attestation-service/releases/tag/v0.8.0
       * https://github.com/confidential-containers/attestation-service
       * Cut a release (AS/RVPS images will be automatically built triggered by release)

- [x] 8. Cut a guest-components v0.8.0 release
        Release: https://github.com/confidential-containers/guest-components/releases/tag/v0.8.0

- [x] 9. Cut a td-shim v0.8.0 release, if changes happened in the project
        Release: https://github.com/confidential-containers/td-shim/releases/tag/v0.8.0
- [x] 10. Update kbs to use the tagged attestation-service and guest-components, cut a release and make image
https://github.com/confidential-containers/kbs/pull/172
       * https://github.com/confidential-containers/kbs/blob/main/src/api/Cargo.toml
         * Change the revision for the `as-types` and `attestation-service` crates (both use `v0.8.0`) and update the lock file
       * https://github.com/confidential-containers/kbs/blob/main/tools/client/Cargo.toml
         * Change the revision for the `as-types` and `kbs_protocol` crates (both use `v0.8.0`)
       * Cut a release
         * kbs image will be automatically built triggered by release, so ensure that the [release workflow](https://github.com/confidential-containers/kbs/actions/workflows/release.yaml) ran successfully

- [x] 11. Update Enclave CC to use the released version of image-rs
    PR: https://github.com/confidential-containers/enclave-cc/pull/272
    * redo step 3, but now using v0.8.0
- [x] 12. Update Kata Containers to the latest released version of:
    PR: https://github.com/kata-containers/kata-containers/pull/8353
    * image-rs (redo step 4, but now using the v0.8.0)
    * attestation-agent (redo step 5, but now using the v0.8.0)
    * td-shim (redo step 6, but now using the v0.8.0)

- [x] 13. Update the operator to use the images generated from the latest commit of both Kata Containers and Enclave CC
    PR: https://github.com/confidential-containers/operator/pull/282
    * redo step 8, but now targetting the latest payload image generated for Kata Containers and Enclave CC

- [x] 14. Make sure all the operator tests are passing

- [x] 15. Cut an Enclave CC release
  Release: https://github.com/confidential-containers/enclave-cc/releases/tag/v0.8.0

- [x] 16. Add a new Kata Containers tag
  Release: https://github.com/kata-containers/kata-containers/tree/CC-0.8.0

- [ ] ~17. Wait for release kata-runtime-payload to be successfully built~
    * After the Kata tag is created wait for (https://github.com/kata-containers/kata-containers/actions/workflows/cc-payload.yaml) to be successfully completed, so the latest commit kata-runtime-payload for the release is created

- [x] 18. Update peer pods to use the release versions and then cut a release following the [documented flow](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/docs/Release-Process.md#cutting-releases)

## Release

- [x] 19. Update the operator to use the release tags coming from Enclave CC and Kata Containers
    PR: https://github.com/confidential-containers/operator/pull/283
    * redo step 8, but now targeting the latest release of the payload image generated for Kata Containers eand Enclave CC

- [x] 20. Update the Operator version
    Commit: https://github.com/confidential-containers/operator/pull/284/commits/30135ece861ba7f1a5e06ea13fe387e2ff7bedbc
    * https://github.com/confidential-containers/operator/blob/main/config/release/kustomization.yaml#L7

- [x] 21. Cut an operator release

- [x] 22. Make sure to update the release notes and tag the confidential-containers repository

    * https://github.com/confidential-containers/documentation/tree/main/releases/v0.8.0.md

- [x] 23. Poke Wainer Moschetta (@wainersm) to update the release to the OperatorHub

**Comment by fitzthum** [comment]
Btw, I am adding @portersrc, @Xynnn007, and @stevenhorsman (ik you have peer pods stuff to do first), and myself to the @confidential-containers/release-champions group

**Comment by wainersm** [comment]
@fitzthum @stevenhorsman and I will be working on peer pods release.

**Comment by stevenhorsman** [comment]
FYI - I've created the peer-pods [RC](https://github.com/confidential-containers/cloud-api-adaptor/releases/tag/v0.8.0-alpha.1) for item 6 and tested in on IBM Cloud for the amd64 and s390x architectures, but I've not heard if it's been tested for any of the other cloud providers

**Comment by mkulke** [comment]
> FYI - I've created the peer-pods [RC](https://github.com/confidential-containers/cloud-api-adaptor/releases/tag/v0.8.0-alpha.1) for item 6 and tested in on IBM Cloud for the amd64 and s390x architectures, but I've not heard if it's been tested for any of the other cloud providers

@stevenhorsman 

I can test Azure. Do we want to create a dedicated tracking issue for this, to keep track of what has been tested?

**Comment by stevenhorsman** [comment]
> I can test Azure. Do we want to create a dedicated tracking issue for this, to keep track of what has been tested?

Good point - Wainer created https://github.com/confidential-containers/cloud-api-adaptor/issues/1548 for tracking the peer pods pieces of things (it's not as nice as a check-list template, but probably better to use than just slack)

**Comment by mkulke** [comment]
> Good point - Wainer created [confidential-containers/cloud-api-adaptor#1548](https://github.com/confidential-containers/cloud-api-adaptor/issues/1548) for tracking the peer pods pieces of things (it's not as nice as a check-list template, but probably better to use than just slack)

Ah, that works, I edited Wainer's post to add a checklist, we should probably link that issue in the message-body above.

**Comment by stevenhorsman** [comment]
FYI - the cause of error that Wainer and Magnus reported on yesterday's call has been identified and would effect any AKS/EKS cluster, not just peer pods, and Wainer (with others) is working on a workaround for it in https://github.com/confidential-containers/operator/pull/284

**Comment by fitzthum** [comment]
I have removed everyone from @confidential-containers/release-champions

**Comment by wainersm** [comment]
In order to check the step 23, I need to merge [Prepare to push v0.8.0 to the Operator Hub](https://github.com/confidential-containers/operator/pull/287) then
[operator cc-operator (0.8.0)](https://github.com/k8s-operatorhub/community-operators/pull/3532). Please more reviews.
