### ISSUE TITLE
Error setting up CoCo for local development

### ISSUE THREAD

**Issue by revoltez** [confidential-containers/confidential-containers#147]
i have a fedora server 38 runing in a vm, when following the quickstart guide it says
 ```
Note If you need to quickly deploy a single-node test cluster, you can use the [run-local.sh script](https://github.com/confidential-containers/operator/blob/main/tests/e2e/run-local.sh) from the operator test suite
```
After installing all the dependencies and cloning the repo, starting `run-local.sh` would give the following error:

```
INFO: Bootstrap the local machine

PLAY [all] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [localhost]

TASK [Install build packages] ********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'fedora'. 'dict object' has no attribute 'fedora'\n\nThe error appears to be in '/root/projects/operator/tests/e2e/ansible/install_build_deps.yml': line 11, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Install build packages\n      ^ here\n"}

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by fidencio** [comment]
@revoltez, you're getting this error because the test scripts are basically expecting to run on "ubuntu" / "centos" machines, which are the systems being used for the baremetal machines and the VMs where we're running those tests.

**Comment by fidencio** [comment]
I'd suggest two options for you:
1. Expand the ansible scripts to support fedora, and a good starting point could be https://github.com/confidential-containers/operator/blob/main/tests/e2e/ansible/group_vars/all -- However, it may get rotten quite easily / quickly unless we also test that on Fedora.
2. Switch to using a Ubuntu / CentOS VM for testing purposes.

If this answers your question, please, let me know and we'll close the issue.

**Comment by fidencio** [comment]
I'm closing this one, feel free to re-open in case the answers didn't help.

**Comment by revoltez** [comment]
@fidencio yes it worked by expanding the ansible script, though it threw some errors so'll be changing to a ubuntu vm (since centos is discontinued), but it yea the issue is solved
