### ISSUE TITLE
[Repository] Combine Attestation-Service & KBS repo

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/confidential-containers#169]
## Description

This issue proposes to combine the two repo https://github.com/confidential-containers/attestation-service and https://github.com/confidential-containers/kbs

## Reason

1. Make the release faster
Everytime we cut a release of KBS/AS, we need to do the following things:
    a. cut a release for `attestation-service`
    b. change the code rev of `attestation-service` and `as-types` in KBS repo to the newest `attestation-service`

if we combined the two repos, what we would do is just
    a. cut a release for the new repo.

2. Let developers feel better (yes)
Now `kbs` repo references `attestation-service`. If we make a change to `attestation-service` repo. To check the correctness of the change, we need to change the rev of `attestation-service` in `kbs` to align with the new version. Such as https://github.com/confidential-containers/attestation-service/pull/90/files and https://github.com/confidential-containers/kbs/pull/76/files

if we combined the two repos, what we would do is just
    a. update the code inside the new repo. The whole PR can describe what it would do, without two different PRs inside different repos.

3. Better for maintaining
The codes inside current `attestation-service` and `kbs` are a little coupled.

After the merging repo, I'd like to tidy the codes for better decoupling and organize them into different crates.

## Steps

Before this, we have already merging repos `image-rs`/`ocicrypt-rs`/`attestation-agent` into `guest-components` in https://github.com/confidential-containers/confidential-containers/issues/89 with great help of @dcmiddle . We can do something similiarly.
1. Move the commits of `attestation-service` repo into `kbs`
2. Archieve `attestation-service` repo
3. Fix the code reference and CIs of `kbs` repo.
4. Rename `kbs` repo to a new name. Maybe it could be named `tenant-components` or something else.

## Timeline

I think it is a good time for us to discuss this. So when the next release starts we can quickly apply this without blocking other developements.

cc @sameo @jialez0  @mkulke

**Comment by mythi** [comment]
What about `kbs_protocol`? I think it also suffers from at least 1. if we continue to maintain the `client` here. Updates/modifications to verifiers/attesters would require coordination even after the proposed change but I'm not sure that's a KBS problem.

To me it looks the main reason for the problems listed here is the `coco-as-builtin` feature that is also enabled by default. That pulls all the verifier dependencies (which in itself is not very developer/user friendly).

Could we solve the challenges by making `kbs` repo less dependent on the TEE details. Attestation-service could run its own validation and push devel images for the `coco-as` based validation.

Merging the two repos is just one solution to fix the problems. Would there be other options?

**Comment by Xynnn007** [comment]
> What about `kbs_protocol`? I think it also suffers from at least 1. if we continue to maintain the `client` here. Updates/modifications to verifiers/attesters would require coordination even after the proposed change but I'm not sure that's a KBS problem.

That's also a critical issue but will not covered by this proposal. About [Attesters](https://github.com/confidential-containers/guest-components/blob/main/attestation-agent/attester/src/lib.rs#L56-L62), we should keep the API as-is because it is now "clean" and straightforward enough. But for [Verifiers](https://github.com/confidential-containers/attestation-service/blob/main/attestation-service/src/verifier/mod.rs#L89-L99), after the merging I would refactoring the API into a more clean one and other related calling codes without changing the overall behavior. e.g.
```rust
#[async_trait]
pub trait Verifier {
    async fn evaluate(
        &self,
        runtime_data: Vec<&[u8]>
    ) -> Result<TeeEvidenceParsedClaim>;
}
```



> To me it looks the main reason for the problems listed here is the `coco-as-builtin` feature that is also enabled by default. That pulls all the verifier dependencies (which in itself is not very developer/user friendly).
> 
> Could we solve the challenges by making `kbs` repo less dependent on the TEE details. Attestation-service could run its own validation and push devel images for the `coco-as` based validation.



I agree to replace `coco-as-builtin` feature with `coco-as-grpc` as default. However the existence of `coco-as-builtin` feature requires us to always check whether it can be built. That is to say, there is no way to make the code truly TEE-independent.

**Comment by mythi** [comment]
> However the existence of `coco-as-builtin` feature requires us to always check whether it can be built. That is to say, there is no way to make the code truly TEE-independent.

But why `coco-as-builtin` exists in the first place? In #119 the proposal was that the KBS is kept generic and the verifiers/AS are independent services. I'd prefer to keep that structure on a repository level also to make it clear there's no strong connection.

**Comment by mythi** [comment]
My preference is to keep the two repositories separate so -1 for this proposal. The argument is that there is no 1:1 relationship between the two and that they are not tightly coupled.

**Comment by mythi** [comment]
> My preference is to keep the two repositories

attestation-agent could also look to follow the work in https://github.com/confidential-containers/kbs/pull/170 to get image updates on every PR/merge for automated `grpc-as` testing.

**Comment by Xynnn007** [comment]
> My preference is to keep the two repositories separate so 👎 for this proposal. The argument is that there is no 1:1 relationship between the two and that they are not tightly coupled.

They are surely not 1:1 relationship, but different level software components. We still have the importing
https://github.com/confidential-containers/kbs/blob/main/src/api/Cargo.toml#L29-L30
https://github.com/confidential-containers/kbs/blob/main/tools/client/Cargo.toml#L17 inside KBS.

> attestation-service could also look to follow the work in [confidential-containers/kbs#170](https://github.com/confidential-containers/kbs/pull/170) to get image updates on every PR/merge for automated `grpc-as` testing.

If we keep AS a separate repo, as `coco-as-builtin` feature https://github.com/confidential-containers/kbs/blob/main/src/api/Cargo.toml#L16 exists every change upon AS will not trigger KBS CI.
