### ISSUE TITLE
[Meeting Request]

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/confidential-containers#172]
### Meeting Title

CoCo CI working group

### Meeting Description

CoCo CI working group meeting: https://docs.google.com/document/d/1gVuJXZzdyZcBg0Vje6n3-uL-SYdgxHzzEw9moU2ycoE

### Meeting date and time

Wed 15:00 UTC

### Meeting recurrence

Weekly

**Comment by fitzthum** [comment]
CNCF Confidential Containers is inviting you to a scheduled Zoom meeting.

Topic: CoCo CI Working Group
Time: Nov 22, 2023 03:00 PM Universal Time UTC
        Every week on Wed, 20 occurrence(s)
        Nov 22, 2023 03:00 PM
        Nov 29, 2023 03:00 PM
        Dec 6, 2023 03:00 PM
        Dec 13, 2023 03:00 PM
        Dec 20, 2023 03:00 PM
        Dec 27, 2023 03:00 PM
        Jan 3, 2024 03:00 PM
        Jan 10, 2024 03:00 PM
        Jan 17, 2024 03:00 PM
        Jan 24, 2024 03:00 PM
        Jan 31, 2024 03:00 PM
        Feb 7, 2024 03:00 PM
        Feb 14, 2024 03:00 PM
        Feb 21, 2024 03:00 PM
        Feb 28, 2024 03:00 PM
        Mar 6, 2024 03:00 PM
        Mar 13, 2024 03:00 PM
        Mar 20, 2024 03:00 PM
        Mar 27, 2024 03:00 PM
        Apr 3, 2024 03:00 PM
Please download and import the following iCalendar (.ics) files to your calendar system.
Weekly: https://zoom.us/meeting/tJcodumrrD0qGdBMbH6aR8wAElXI_Dl-bx6k/ics?icsToken=98tyKuCrqzoqGdaTsBqDRowqGYj4c-nzpiFfjad_sR3NVSFhOhTXE-56G41bHJXS

Join Zoom Meeting
https://zoom.us/j/93510326034

Meeting ID: 935 1032 6034

---

One tap mobile
+16469313860,,93510326034# US
+19292056099,,93510326034# US (New York)

---

Dial by your location
• +1 646 931 3860 US
• +1 929 205 6099 US (New York)
• +1 309 205 3325 US
• +1 312 626 6799 US (Chicago)
• +1 301 715 8592 US (Washington DC)
• +1 305 224 1968 US
• +1 669 444 9171 US
• +1 669 900 6833 US (San Jose)
• +1 689 278 1000 US
• +1 719 359 4580 US
• +1 253 205 0468 US
• +1 253 215 8782 US (Tacoma)
• +1 346 248 7799 US (Houston)
• +1 360 209 5623 US
• +1 386 347 5053 US
• +1 507 473 4847 US
• +1 564 217 2000 US
• 877 853 5247 US Toll-free
• 888 788 0099 US Toll-free

Meeting ID: 935 1032 6034

Find your local number: https://zoom.us/u/aeL8Ze5KN
