### ISSUE TITLE
Unable to install runtime classes

### ISSUE THREAD

**Issue by stlankes** [confidential-containers/confidential-containers#181]
I was able to install the operator. However, I am not able to install the runtime classes:

```
$ kubectl get pods -n confidential-containers-system
NAME                                             READY   STATUS    RESTARTS   AGE
cc-operator-controller-manager-858dd6c84-5zz2q   2/2     Running   0          77m
$ kubectl apply -k github.com/confidential-containers/operator/config/samples/ccruntime/default?ref=v0.8.0
ccruntime.confidentialcontainers.org/ccruntime-sample created
$ kubectl get runtimeclass
No resources found
```

How can I find out why the runtime classes are not installed?

**Comment by fitzthum** [comment]
You might want to make sure that your node has the correct labels. Should be something like `node.kubernetes.io/worker=`

**Comment by stlankes** [comment]
You are right. I added some the label but with  a typo... I fixed it and now it works.

Thanks for the help!
