### ISSUE TITLE
Supported rust version

### ISSUE THREAD

**Issue by portersrc** [confidential-containers/confidential-containers#193]
Recently I noticed both kbs and guest-components were fiddling with versioning due to rust-nightly, e.g. see:
  https://github.com/confidential-containers/kbs/actions/runs/7886823519/job/21520785968
  https://github.com/confidential-containers/guest-components/issues/470

These are the respective workflows that test with different rust versions. They test with stable, nightly, beta, and 1.72.0 (though they are a little inconsistent across the files):
kbs:
  https://github.com/confidential-containers/kbs/blob/main/.github/workflows/kbs-rust.yml#L25-L28

guest-components:
  https://github.com/confidential-containers/guest-components/blob/main/.github/workflows/aa_sample_keyprovider.yml#L23-L25
  https://github.com/confidential-containers/guest-components/blob/main/.github/workflows/image_rs_build.yml#L31-L33
  https://github.com/confidential-containers/guest-components/blob/main/.github/workflows/ocicrypt_rs_build.yml#L28-L30

I suggest sticking solely to a specific version and updating intentionally (e.g. 1.72.0 was chosen for some reason in the past), or I suggest stable (which at a 6-week cadence is very frequent). I suggest against nightly or beta, and I suggest against using any kind of matrix in the workflow for this.

I'm not a rust expert, so maybe there is a good reason to keep all (or some) of what we're already doing. But it looked like we were handling failing test cases for no clear benefit.

**Comment by mythi** [comment]
I started a similar topic in Slack last week: https://cloud-native.slack.com/archives/C039JSH0807/p1707459616139839

My question was more 'about when to bump the version' since in enclave-cc I'm seeing dependabot updates that depend on a version newer than 1.72.0. Perhaps moving to use `stable` would give the bump automatically but in that case a nightly CI build job using, e.g., `beta` is needed to be able to spot any potential future breakages.

**Comment by jodh-intel** [comment]
In Kata Containers, we've been maintaining a YAML database of external dependencies (`versions.yaml`) for the last six years, including rust versions (for the last four years). Basically, every possible version is pinned. Prior to introducing the versions database, we'd been burnt too many times when the "sands shifted underneath us". There is minimal overhead maintaining the file, it's human and machine readable and of course tracked by git. Essentially, it's essential :smile:

## Kata versions database

- https://github.com/kata-containers/kata-containers/blob/74c8d243ea53c206d8238b51ad688e83080fe04d/versions.yaml#L357..L365

Here are the current rust version details:

```yaml
  rust:
    description: "Rust language"
    notes: "'version' is the default minimum version used by this project."
    version: "1.72.0"
    meta:
      description: |
        'newest-version' is the latest version known to work when
        building Kata
      newest-version: "1.72.0"
```

## Update the rust version(s)

As shown above, we define two versions: the minimum usable version of rust and the newest usable version. We bump `.languages.rust.meta.newest-version` periodically, generally after new rust releases, to see if we find any issues and if not, update `.languages.rust.version`. At that point the versions are the same, as they are now. Theoretically, we could create a GH action to update `.languages.rust.meta.newest-version` speculatively and raise a PR if the CI passes.

## Accessing the database

We have a `get_from_kata_deps()` shell function to extract version details from that database here:

- https://github.com/kata-containers/kata-containers/blob/main/tests/common.bash#L466..L475

### Example of accessing the database

And here's an example of calling `get_from_kata_deps "languages.rust.meta.newest-version"` to obtain the newest version of rust:

- https://github.com/kata-containers/kata-containers/blob/main/tests/install_rust.sh#L20

**Comment by Xynnn007** [comment]
I like the idea. Everytime rust publishes new version especially `nightly`, we would face some unexpected errors upon CI. A fixed version of compiler will resolve this. What we need to do is update the version periodically.

Different from kata-containers, kbs and guest-components are being test via github action's `actions-rs/cargo@v1`. So a possible start might be to fix the versions inside the GH workflow yaml?

**Comment by mythi** [comment]
I think the proposal was to use stable releases _only_ but stick to a version that we manually bump every time a new stable release is made. Any code fixing/updating can be done at that time

**Comment by portersrc** [comment]
@jodh-intel's details of what kata is doing is really helpful and a good way to do this, in my opinion. Notice also they're not testing against rust-nightly in their CI anywhere (from what I can tell).

@mythi is correct: I was suggesting we pin to a specific version and bump it deliberately.

After looking at this a bit more, I think the thing to do is:
1. Support a specific rust version. That's 1.72.0 currently. (`clap` fails on this, so now could be a time to bump, as @mythi points out.)
2. Test two rust versions in the workflows: 1.72.0 and stable. The pinned version is because we support it. The stable version is to catch upcoming issues.
3. Drop nightly altogether. Running CI checks against stable already keeps us on top of things when we want to bump. Further, as I understand it, nightly is experimental and those features may never hit stable (so why field any static checks against it, unless you're, say, developing the Rust language itself).
4. Drop beta altogether. Beta becomes stable, but we're pinned (almost always) prior to stable. So we just need CI jobs against stable if we're trying to catch issues early.

Looking at @Xynnn007's recent PRs, thanks for the initiative; I'd just drop nightly altogether, though, as mentioned above.

**Comment by portersrc** [comment]
I noticed another good reason to implement something like what @jodh-intel is showing for kata. We have stuff like this right now in coco (just grabbing rust-latest):
  https://github.com/confidential-containers/kbs/blob/main/kbs/docker/Dockerfile.coco-as-grpc#L1
Replacing that with a pinned version is error-prone, but we can do something like this with kata's approach (ensuring the toolchain matches what is supported):
  https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/static-build/coco-guest-components/Dockerfile#L28

**Comment by mkulke** [comment]
> In Kata Containers, we've been maintaining a YAML database of external dependencies (`versions.yaml`) for the last six years, including rust versions (for the last four years). Basically, every possible version is pinned. Prior to introducing the versions database, we'd been burnt too many times when the "sands shifted underneath us". There is minimal overhead maintaining the file, it's human and machine readable and of course tracked by git. Essentially, it's essential 😄
> 
> ## Kata versions database
> * https://github.com/kata-containers/kata-containers/blob/74c8d243ea53c206d8238b51ad688e83080fe04d/versions.yaml#L357..L365
> 
> Here are the current rust version details:
> 
> ```yaml
>   rust:
>     description: "Rust language"
>     notes: "'version' is the default minimum version used by this project."
>     version: "1.72.0"
>     meta:
>       description: |
>         'newest-version' is the latest version known to work when
>         building Kata
>       newest-version: "1.72.0"
> ```
> 
> ## Update the rust version(s)
> As shown above, we define two versions: the minimum usable version of rust and the newest usable version. We bump `.languages.rust.meta.newest-version` periodically, generally after new rust releases, to see if we find any issues and if not, update `.languages.rust.version`. At that point the versions are the same, as they are now. Theoretically, we could create a GH action to update `.languages.rust.meta.newest-version` speculatively and raise a PR if the CI passes.
> 
> ## Accessing the database
> We have a `get_from_kata_deps()` shell function to extract version details from that database here:
> 
> * https://github.com/kata-containers/kata-containers/blob/main/tests/common.bash#L466..L475
> 
> ### Example of accessing the database
> And here's an example of calling `get_from_kata_deps "languages.rust.meta.newest-version"` to obtain the newest version of rust:
> 
> * https://github.com/kata-containers/kata-containers/blob/main/tests/install_rust.sh#L20

coco/cloud-api-adaptor has also adopted this. there's a slight yq v3 vs v4 annoyance, but otherwise that works well.

**Comment by portersrc** [comment]
Fixed by https://github.com/confidential-containers/kbs/pull/331 and https://github.com/confidential-containers/guest-components/pull/477
