### ISSUE TITLE
Enforce signoffs / DCO in web commits

### ISSUE THREAD

**Issue by dcmiddle** [confidential-containers/confidential-containers#206]
We don't get a ton of web based commits but if we do they are more difficult to remediate missing signed-off-by.

At the org level we can enforce that with a checkbox
https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/#how-to-enable-required-signoffs-for-an-organization

Settings->code->repository->repository defaults->`Commit signoff`

![image](https://github.com/confidential-containers/confidential-containers/assets/4999494/e5375d2f-8b77-4f4a-a176-97ca9fdeab7c)

Requires Org owner permissions.

**Comment by fitzthum** [comment]
Enabled
