### ISSUE TITLE
Error deploying test pod 

### ISSUE THREAD

**Issue by BigThor12** [confidential-containers/confidential-containers#207]
Hi, I'm trying to do some test using Confidential Containers on a server with Intel SGX. I followed the quickstart to do the installation, but when I try to deploy the test pod with the enclave-cc runtime I get this error:
<img width="390" alt="CoCo5" src="https://github.com/confidential-containers/confidential-containers/assets/100221999/6af6c6a9-8517-4464-bc00-1f47eae60311">
I did ```kubectl describe``` to get more information and seems like it can't get the SGX evidence
<img width="768" alt="CoCo3" src="https://github.com/confidential-containers/confidential-containers/assets/100221999/2b5c2289-69b9-4b75-b950-8566ddbe9065">
I have the attestation module deployed in docker, just like it appears in the quickstart:
<img width="767" alt="CoCoAtt" src="https://github.com/confidential-containers/confidential-containers/assets/100221999/2b15e486-1b0f-4ae1-8ea6-0c606dc5070f">
Here you can see the log of the kbs container when I try to deploy the pod:
<img width="770" alt="CoCo4" src="https://github.com/confidential-containers/confidential-containers/assets/100221999/e7c4530a-7808-4ee1-a2a6-e50a0695c510">
I've also tried to change some parameters of the attestation configuration, but nothing seems to fix this issue. I have the Intel PCCS and Intel AESMD services running.
Any idea where's the issue and how can I solve it?
Thanks in advance

**Comment by qiaofu1024** [comment]
I had the same problem at#212，You solved it？brother @BigThor12

**Comment by BigThor12** [comment]
Hi @qiaofu1024 , I still haven't been able to solve the problem.

**Comment by mythi** [comment]
> Hi @qiaofu1024 , I still haven't been able to solve the problem.

can we close this and follow-up in #212
