### ISSUE TITLE
[CNCF]kata 机密容器方案虚拟机中pull dockerhub  镜像失败

### ISSUE THREAD

**Issue by panpingsheng** [confidential-containers/confidential-containers#218]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) that this issue will track:*

国内dockerhub 不稳定，导致机密容器虚拟机中无法从dockerhub 仓库中pull 镜像，主机上可以通过设置国内加速源的方法规避，如
higon@higon:~$ cat /etc/docker/daemon.json
{
	"registry-mirrors": ["https://registry.docker-cn.com","https://s3d6l2fh.mirror.aliyuncs.com"]
}
机密容器虚拟机能否也提供对应的方法去规避这个问题，目前可以通过设置代理的方法规避，方法如下：
kernel_params = "agent.https_proxy=http://10.61.40.54:7890 agent.no_proxy=*.hygon.cn,10.*.*.*,172.*.*.* agent.enable_signature_verification=false "
但是国内客户不一定有**外网代理**，希望提供类似主机的规避方案

**Comment by Xynnn007** [comment]
Can close as mentioned in https://github.com/confidential-containers/guest-components/issues/601

**Comment by panpingsheng** [comment]
你发过来的邮件怎么都是乱码啊，什么都看不到，再发一次吧。

**Comment by panpingsheng** [comment]
放错地方了

**Comment by peng-yq** [comment]
> ### Parts of the [CNCF onboarding issue](https://github.com/cncf/sandbox/issues/216) tracked by this issue
> _This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/sandbox/issues/216) that this issue will track:_
> 
> 国内dockerhub 不稳定，导致机密容器虚拟机中无法从dockerhub 仓库中pull 镜像，主机上可以通过设置国内加速源的方法规避，如 higon@higon:~$ cat /etc/docker/daemon.json { "registry-mirrors": ["https://registry.docker-cn.com","https://s3d6l2fh.mirror.aliyuncs.com"] } 机密容器虚拟机能否也提供对应的方法去规避这个问题，目前可以通过设置代理的方法规避，方法如下： kernel_params = "agent.https_proxy=http://10.61.40.54:7890 agent.no_proxy=_.hygon.cn,10._._._,172._._.* agent.enable_signature_verification=false " 但是国内客户不一定有**外网代理**，希望提供类似主机的规避方案

哥们儿，你机密容器是按照官方的manual跑起来的吗？

**Comment by panpingsheng** [comment]
你发过来的邮件怎么都是乱码啊，什么都看不到，再发一次吧。
