### ISSUE TITLE
Failed to deploy encrypted image on enclave-cc hardware

### ISSUE THREAD

**Issue by BastienFaivre** [confidential-containers/confidential-containers#220]
Hi everyone,

I am trying to deploy an encrypted image on `enclave-cc` with the hardware version. I've followed the [quickstart](https://github.com/confidential-containers/confidential-containers/blob/main/quickstart.md) and I am stuck at the last step. For context, here is what I've done so far:

First, I use `kind` to get a cluster:

```bash
kind create cluster --image "kindest/node:v1.29.2" -n coco --config operator/tests/e2e/enclave-cc-kind-config.yaml --wait 120s
kubectl label node coco-worker node.kubernetes.io/worker=
```

I will use the version `v0.8.0`, so I deploy the operator as well as `enclave-cc`:

```bash
export RELEASE_VERSION=v0.8.0
kubectl apply -k "github.com/confidential-containers/operator/config/release?ref=${RELEASE_VERSION}"
kubectl apply -k github.com/confidential-containers/operator/config/samples/enclave-cc/hw?ref=${RELEASE_VERSION}
```

At this point, everything is running and, when executing `kubectl get runtimeClass`, I indeed get `enclave-cc`.

Then, I followed the section [Encrypted and/or signed images with attestation](https://github.com/confidential-containers/confidential-containers/blob/main/quickstart.md#encrypted-andor-signed-images-with-attestation). Again, everything run without problem, except the last step _Deploy encrypted image as a CoCo workload on CC HW_.

My first question is, should the file `/opt/confidential-containers/share/defaults/kata-containers/configuration-<RUNTIME_CLASS_SUFFIX>.toml` already exist? On my side, the `defaults` directory does not exist. Furthermore, is the suffix of `enclave-cc` just `cc`? What should the file content look like?

If I try to deploy the encrypted image without this previous configuration, I get the following problem with `overlayfs`:

```
Error: failed to create containerd task: failed to create shim task: failed to mount rootfs component &{overlay overlay [index=off workdir=/run/enclave-cc/app/ubuntu/work upperdir=/run/enclave-cc/app/ubuntu/upper lowerdir=/run/containerd/agent-enclave/6260240ef5f9bcbbc2c6e88da660d906afc3eb35db31074e1fe7cd7113675132/merged/rootfs/images/sha256_35a88802559dd2077e584394471ddaa1a2c5bfd16893b829ea57619301eb3908:/opt/confidential-containers/share/enclave-cc-boot-instance/rootfs]}: no such file or directory: unknown
```

I aware that this `overlayfs` is a known issue with `enclave-cc` and `kind` as mentioned in the [prerequisites](https://github.com/confidential-containers/confidential-containers/blob/main/quickstart.md#prerequisites). This is why, as explained, I am using the sample configuration `operator/tests/e2e/enclave-cc-kind-config.yaml`, which should not lead to this issue.

Does anyone know why I am still getting this `overlayfs` issue? What am I missing?

Thank you in advance for your help!

**Comment by fitzthum** [comment]
cc @mythi (I think he's on vacation rn), @Xynnn007

**Comment by mythi** [comment]
> Then, I followed the section [Encrypted and/or signed images with attestation](https://github.com/confidential-containers/confidential-containers/blob/main/quickstart.md#encrypted-andor-signed-images-with-attestation)

Did you also follow the `enclave-cc` specific notes? I've never tried to run the HW mode enclave-cc in a `kind` cluster. My best-known-config is to just set up an Azure k8s cluster w/ SGX and simply copy&paste the two operator deployments like mentioned above.
