### ISSUE TITLE
Error: failed to create containerd task: failed to create shim task: failed to mount rootfs component

### ISSUE THREAD

**Issue by qiaofu1024** [confidential-containers/confidential-containers#231]
@mythi  Long time no see, hi brother, help me, follow the error message, i dont't known!

`Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  2m21s                 default-scheduler  Successfully assigned default/enclave-cc-pod to k8s-node01
  Normal   Pulled     60s (x5 over 2m21s)   kubelet            Container image "ghcr.io/confidential-containers/test-container-enclave-cc:encrypted" already present on machine
  Normal   Created    59s (x5 over 2m21s)   kubelet            Created container hello-world
  Warning  Failed     59s (x5 over 2m21s)   kubelet            Error: failed to create containerd task: failed to create shim task: failed to mount rootfs component &{overlay overlay [index=off workdir=/run/enclave-cc/app/hello-world/work upperdir=/run/enclave-cc/app/hello-world/upper lowerdir=/run/containerd/agent-enclave/86a1cb7159f40d60af90c66ad2da856c4a74072717b80950d4c3ea83d172bcfd/merged/rootfs/images/sha256_87c04269aee78236edb6281bfafe057bec7378eeafdd1fc44bf88e6a74564552:/opt/confidential-containers/share/enclave-cc-boot-instance/rootfs]}: no such file or directory: unknown
  Warning  BackOff    19s (x10 over 2m19s)  kubelet            Back-off restarting failed container hello-world in pod enclave-cc-pod_default(e858faf5-27d7-4e81-9ab3-fa0fb8dcfb24)`

**Comment by mythi** [comment]
Get the enclave-agent logs same as in https://github.com/confidential-containers/confidential-containers/issues/212#issuecomment-2126791797
