### ISSUE TITLE
Runtime “kata-qemu-tdx” failed to create containerd container -- object with key already exists

### ISSUE THREAD

**Issue by qzheng527** [confidential-containers/confidential-containers#257]
### Summary
I got a TDX machine in which CVM guest could be started successfully.
I followed the [doc](https://github.com/confidential-containers/operator/blob/v0.10.0/docs/INSTALL.md) to instal CoCo operator and try  deploy the simple nginx sample but failed.
**Error: failed to create containerd container: create instance 4: object with key "4" already exists: unknown**

```
  Normal   Scheduled  6s    default-scheduler  Successfully assigned default/nginx to kx-archercity
  Normal   Pulling    1s    kubelet            Pulling image "bitnami/nginx:1.22.0"
  Normal   Pulled     1s    kubelet            Successfully pulled image "bitnami/nginx:1.22.0" in 244ms (244ms including waiting)
  Warning  Failed     1s    kubelet            Error: failed to create containerd container: create instance 4: object with key "4" already exists: unknown
```

At this time, I can log in the CVM by `kata-runtime exec <id>`. But I couldn't find any useful info.

### Details
The K8S version is 1.28.
The Kata installed in /opt/kata is 3.10.1.
The CoCo operator version is v0.10.0.
The nginx yam file is as below.
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  annotations:
    io.containerd.cri.runtime-handler: kata-qemu-tdx
spec:
  containers:
  - image: bitnami/nginx:1.22.0
    name: nginx
    imagePullPolicy: Always
  dnsPolicy: ClusterFirst
  runtimeClassName: kata-qemu-tdx
```

Can anyone give some clues or point out the direction to debug?

**Comment by qzheng527** [comment]
I got it work.
Probably it was because I had a preinstalled kata 3.10.1 but the operator would install a kata as well which may cause conflict.
After removing the old kata and reinstall the operator （v0.10.0 which install kata 3.9.0), the nginx sample works.

**Comment by fffmonkeyking-new** [comment]
Warning  FailedCreatePodSandBox  3m32s (x415 over 93m)  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd container: create instance 6: object with key "6" already exists: unknown
。。。、、、
I encountered the same problem;
But I didn't install kata, I directly installed coco v0.11.0.
This is a very common problem, I don't know how to avoid or solve it. . .
