### ISSUE TITLE
Quickstart help wanted

### ISSUE THREAD

**Issue by peng-yq** [confidential-containers/confidential-containers#271]
## Description

I am following the Quickstart guide to deploy the Confidential Containers, but I am encountering an issue when creating custom resource for kata. Despite having the CRD installed, I receive an error indicating that there are no matches for kind "CcRuntime" in version "confidentialcontainers.org/v1beta1". I have no idea to figure it out. And all the steps before it have been done.

```shell
➜  coco kubectl get namespace                                                                                      

NAME                             STATUS   AGE
confidential-containers-system   Active   73m
default                          Active   11h
kube-flannel                     Active   <invalid>
kube-node-lease                  Active   11h
kube-public                      Active   11h
kube-system                      Active   11h
➜  coco kubectl get crds                                                                                           

NAME                                    CREATED AT
ccruntimes.confidentialcontainers.org   2024-11-26T07:58:17Z
➜  coco kubectl get pods -n confidential-containers-system
NAME                                              READY   STATUS    RESTARTS   AGE
cc-operator-controller-manager-7f8db55b55-wj6pq   2/2     Running   0          88m

➜  coco kubectl apply -k "github.com/confidential-containers/operator/config/samples/ccruntime/default?ref=v0.10.0"

error: resource mapping not found for name: "ccruntime-sample" namespace: "" from "github.com/confidential-containers/operator/config/samples/ccruntime/default?ref=v0.10.0": no matches for kind "CcRuntime" in version "confidentialcontainers.org/v1beta1"
ensure CRDs are installed first
```

## Environment

```shell
# os
➜  coco uname -a
Linux test 6.8.0-47-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

# kubelet
➜  coco kubelet --version
Kubernetes v1.29.11

# kubectl 
➜  coco kubectl version                                   
Client Version: v1.29.11
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.11

# kubeadm 
➜  coco kubeadm version  
kubeadm version: &version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.11", GitCommit:"960a2f019319ab5f7ac1c256efcc180a4113343a", GitTreeState:"clean", BuildDate:"2024-11-20T13:44:59Z", GoVersion:"go1.22.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by peng-yq** [comment]
Today I tried `kubectl apply -k "github.com/confidential-containers/operator/config/samples/ccruntime/default?ref=v0.10.0"` again. No error was reported and the creation was successful. However, subsequent verification found that it was not successful. How can I solve and troubleshoot this problem?

```shell
➜  coco kubectl get crd | grep ccruntime
ccruntimes.confidentialcontainers.org   2024-11-26T07:58:17Z
➜  coco kubectl explain ccruntimes.confidentialcontainers.org
GROUP:      confidentialcontainers.org
KIND:       CcRuntime
VERSION:    v1beta1

DESCRIPTION:
    CcRuntime is the Schema for the ccruntimes API
    
FIELDS:
  apiVersion    <string>
    APIVersion defines the versioned schema of this representation of an object.
    Servers should convert recognized schemas to the latest internal value, and
    may reject unrecognized values. More info:
    https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

  kind  <string>
    Kind is a string value representing the REST resource this object
    represents. Servers may infer this from the endpoint the client submits
    requests to. Cannot be updated. In CamelCase. More info:
    https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

  metadata      <ObjectMeta>
    Standard object's metadata. More info:
    https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata

  spec  <Object>
    CcRuntimeSpec defines the desired state of CcRuntime

  status        <Object>
    CcRuntimeStatus defines the observed state of CcRuntime


➜  coco kubectl apply -k "github.com/confidential-containers/operator/config/samples/ccruntime/default?ref=v0.10.0"

ccruntime.confidentialcontainers.org/ccruntime-sample unchanged
➜  coco kubectl get pods -n confidential-containers-system
NAME                                              READY   STATUS    RESTARTS   AGE
cc-operator-controller-manager-7f8db55b55-wj6pq   2/2     Running   0          22h
➜  coco kubectl get runtimeclass
No resources found
```
In addition, due to the network limit in my area, I couldn't pull the image, so I could only pull it manually and then import it into the server. I looked at the corresponding yaml file and pulled the following image. I don't know if there is any problem with this. But if it is an image problem, after using `coco kubectl get pods -n confidential-containers-system`, you can see the specific container, and its status is `ImagePullBackoff`, but I don't see anything here.

```shell
docker pull quay.io/confidential-containers/reqs-payload:12e8fbc72e927f9d684efe2e1214937f8b0544fc
docker pull quay.io/kata-containers/kata-deploy:3.9.0
docker pull quay.io/kata-containers/kata-deploy:stable
```

**Comment by peng-yq** [comment]
Help wanted : ( ! @dubek @beraldoleal @bergwolf @fidencio

**Comment by mythi** [comment]
> Today I tried `kubectl apply -k "github.com/confidential-containers/operator/config/samples/ccruntime/default?ref=v0.10.0"` again.

You might be missing some node labels described in the [pre-requisites](https://github.com/confidential-containers/confidential-containers/blob/main/quickstart.md#prerequisites).

Also, since you seem to suffer from image pull issues, you might want to try `v0.11.0` since it now allows to modify `ImagePullPolicy` to get your images pre-pulled. See https://github.com/confidential-containers/operator/issues/395.

**Comment by mythi** [comment]
> However, I don't think the issue is with the labels

Something seems to block the operator (controller pod) to reconcile `CcRuntime` resources. Missing labels or some other pre-condition would explain why you don't see any other coco installation pods running.

> Are you suggesting that I should apply version `v0.11.0` for both deploying the operator and creating the custom resource for Kata?

Both

**Comment by peng-yq** [comment]
> > However, I don't think the issue is with the labels
> 
> Something seems to block the operator (controller pod) to reconcile `CcRuntime` resources. Missing labels or some other pre-condition would explain why you don't see any other coco installation pods running.
> 
> > Are you suggesting that I should apply version `v0.11.0` for both deploying the operator and creating the custom resource for Kata?
> 
> Both

Indeed, the issue was with the node labels. After re-labeling the master node with the worker label, the CoCo installation pod appeared.

I've updated both components to version v0.11.0 and pre-downloaded the `reqs-payload` image, but it still attempts to pull the image. Given the network restrictions on our server, where DNS services are banned, we can only pull images on another server and then import them. Is this because the `ImagePullPolicy` is set to `Always`? Where can I modify this setting? 

```shell
➜  coco kubectl describe pod cc-operator-pre-install-daemon-d7lh7 -n confidential-containers-system
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  16m                 default-scheduler  Successfully assigned confidential-containers-system/cc-operator-pre-install-daemon-d7lh7 to test
  Normal   Pulling    13m (x4 over 16m)   kubelet            Pulling image "quay.io/confidential-containers/reqs-payload:7b06283a5be08f4d83f2bf15851d55739bf27ec5"
  Warning  Failed     13m (x4 over 15m)   kubelet            Failed to pull image "quay.io/confidential-containers/reqs-payload:7b06283a5be08f4d83f2bf15851d55739bf27ec5": failed to pull and unpack image "quay.io/confidential-containers/reqs-payload:7b06283a5be08f4d83f2bf15851d55739bf27ec5": failed to resolve reference "quay.io/confidential-containers/reqs-payload:7b06283a5be08f4d83f2bf15851d55739bf27ec5": failed to do request: Head "https://quay.io/v2/confidential-containers/reqs-payload/manifests/7b06283a5be08f4d83f2bf15851d55739bf27ec5": dial tcp: lookup quay.io: no such host
  Warning  Failed     13m (x4 over 15m)   kubelet            Error: ErrImagePull
  Warning  Failed     12m (x6 over 15m)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    61s (x53 over 15m)  kubelet            Back-off pulling image "quay.io/confidential-containers/reqs-payload:7b06283a5be08f4d83f2bf15851d55739bf27ec5"
➜  coco sudo ctr -n k8s.io images list | grep reqs-payload:7b06283a5be08f4d83f2bf15851d55739bf27ec5
quay.io/confidential-containers/reqs-payload:7b06283a5be08f4d83f2bf15851d55739bf27ec5 application/vnd.oci.image.manifest.v1+json                sha256:6f98b35b33fa06d7b975c27b66449ef0e358050c0db4affedeccf4be69dcd6d0 238.6 MiB linux/amd64                                                                  io.cri-containerd.image=managed
```

**Comment by peng-yq** [comment]
> > Where can I modify this setting?
> 
> In the `CcRuntime` yaml under `ccRuntime.Spec.Config.ImagePullPolicy` path.

Are you referring to [this file](https://github.com/confidential-containers/operator/blob/v0.11.0/config/samples/ccruntime/base/ccruntime.yaml)? I didn't find the ImagePullPolicy field there, so I need to add `imagePullPolicy: IfNotPresent`, correct? Also, since I initially applied the configuration using `kubectl apply -k "github.com/confidential-containers/operator/config/samples/ccruntime/default?ref=v0.11.0"`, how should I proceed with modifications? Should I pull the files locally, modify them, and then apply using `kubectl apply -f`? If so, which YAML files should I apply and in what order? Or should I fork the repository, make the changes, and continue using `kubectl apply -k`?

Apologies if my questions seem basic; I'm new to Kubernetes. Thank you for your help.

**Comment by qiaofu1024** [comment]
git clone
cd ./operator/config/samples/ccruntime/default
kubectl apply -d .

# After modification
kubectl apply -k .

> > > Where can I modify this setting?
> > 
> > 
> > In the `CcRuntime` yaml under `ccRuntime.Spec.Config.ImagePullPolicy` path.
> 
> Are you referring to [this file](https://github.com/confidential-containers/operator/blob/v0.11.0/config/samples/ccruntime/base/ccruntime.yaml)? I didn't find the ImagePullPolicy field there, so I need to add `imagePullPolicy: IfNotPresent`, correct? Also, since I initially applied the configuration using `kubectl apply -k "github.com/confidential-containers/operator/config/samples/ccruntime/default?ref=v0.11.0"`, how should I proceed with modifications? Should I pull the files locally, modify them, and then apply using `kubectl apply -f`? If so, which YAML files should I apply and in what order? Or should I fork the repository, make the changes, and continue using `kubectl apply -k`?
> 
> Apologies if my questions seem basic; I'm new to Kubernetes. Thank you for your help.

**Comment by peng-yq** [comment]
> imagePullPolicy: IfNotPresent

Thank you, it's resolved. However, `kubectl apply -d .` is incorrect; it should be `kubectl apply -k .`.

**Comment by mythi** [comment]
Great that it's working now!

> it should be `kubectl apply -k .`.

I believe the idea was to show how to remove the old installation: `kubectl delete -k .`.

**Comment by qiaofu1024** [comment]
Sorry, my problem. Yes, thanks to Mikko for the correction.
