### ISSUE TITLE
Add a codeowner file for each repo

### ISSUE THREAD

**Issue by sameo** [confidential-containers/confidential-containers#31]
It's a simple (the simplest?) way to track who is maintaining each repo.

For repos that have a maintainer team associated to it, the CODEOWNERS file should just be a copy of the team.

**Comment by ariel-adam** [comment]
@sameo is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by mythi** [comment]
- https://github.com/confidential-containers/trustee/pull/488
- https://github.com/confidential-containers/guest-components/pull/704
- https://github.com/confidential-containers/operator/pull/438
- https://github.com/confidential-containers/cloud-api-adaptor/pull/2034
- https://github.com/confidential-containers/trustee-operator/pull/45
- https://github.com/confidential-containers/enclave-cc/pull/29

Closing as completed.
