### ISSUE TITLE
Follow Cryptography Best Practices

### ISSUE THREAD

**Issue by dcmiddle** [confidential-containers/confidential-containers#44]
From https://bestpractices.coreinfrastructure.org/en/projects/5719#security

(Condensed)
Do not write your own crypto. Use FLOSS implementations.
Use NIST 2030 key lengths.
Don't use old broken or weak algorithms (e.g. SHA-1).
Use random number generators designed for cryptographic use.

Perhaps the best way to satisfy this badge criteria is to discuss where we are using cryptography and understand whether those areas meet the full list of best practices defined at the badge link.

**Comment by dcmiddle** [comment]
Please list here which components are using cryptography especially any custom implementations.

**Comment by sameo** [comment]
image-rs is the one that comes to mind first. It depends on the `sha2` and `opengpg-sequoia` crypto crates

**Comment by fitzthum** [comment]
AA OpenSSL and the `aes_gcm` and `rsa` crate depending on which KBC you use. `EAA_KBC` use `rats-tls`. I'm not sure what the crypto situation is there.

**Comment by dcmiddle** [comment]
ocicrypt-rs uses aes, ctr, aes-gcm, josekit, rand, and sha2 crates

aes and ctr are used together for aes-ctr mode 
aes-gcm and josekit are used in the keyprovider
rand is used for aes-ctr key and nonce generation. It is called with thread_rng which according to the docs uses the same rng as StdRng which is cryptographically secure.

**Comment by dcmiddle** [comment]
This issue and the importance of using Cryptography best practices was discussed in the community meeting 2022-07-21.
Minutes: https://docs.google.com/document/d/1E3GLCzNgrcigUlgWAZYlgqNTdVwiMwCRTJ0QnJhLZGA/edit#heading=h.mg5zidnb7moc

**Comment by dcmiddle** [comment]
Resolved ahead of first release. Consider opening a new issue for future releases.

**Comment by jyao1** [comment]
Question for `rand` crate: https://rust-random.github.io/book/guide-rngs.html#not-a-crypto-library. Is this really secure?
Why not use the one in openssl, or ring?

**Comment by dcmiddle** [comment]
@arronwy ^

**Comment by ariel-adam** [comment]
@dcmiddle is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by dcmiddle** [comment]
Awaiting resolution of https://github.com/confidential-containers/td-shim/issues/294

**Comment by jyao1** [comment]
I closed https://github.com/confidential-containers/td-shim/issues/294. We can use sha2 crate directly.

https://github.com/fortanix/rust-mbedtls is also OK, after its PR 211 is merged.

**Comment by dcmiddle** [comment]
Remaining TODO for each crypto use verify: 

- [x] Do not write your own crypto. Use FLOSS implementations.
- [ ] Use NIST 2030 key lengths.
- [x] Don't use old broken or weak algorithms (e.g. SHA-1).
- [ ] Use random number generators designed for cryptographic use.

**Comment by ariel-adam** [comment]
@dcmiddle is this targeted for 0.7.0 or maybe we should just remove the specific release tag if it's ongoing and does affect a specific release?

**Comment by dcmiddle** [comment]
Regarding Use NIST 2030 key lengths.
Verified ocicrypt blockcipher uses aes256. 
https://github.com/confidential-containers/guest-components/blob/main/ocicrypt-rs/src/blockcipher/mod.rs#L22
And the ocicrypt keywrapper has examples with appropriate key lengths.
https://github.com/confidential-containers/guest-components/blob/main/ocicrypt-rs/data/generate_keys.md?plain=1

**Comment by dcmiddle** [comment]
Regarding Use Random number generators designed for cryptographic use:
ocicrypt uses openssl or ring (selected by feature)
attestation agent uses the osrng of rust rand 
confidential-data-hub uses thread_rng which according to the documentation "should be secure"
In the future we should consider consolidating these so we aren't using different random libraries.
