### ISSUE TITLE
Define Static Code Analysis in CI

### ISSUE THREAD

**Issue by dcmiddle** [confidential-containers/confidential-containers#46]
From https://bestpractices.coreinfrastructure.org/en/projects/5719#analysis

At least one static code analysis tool (beyond compiler warnings and "safe" language modes) MUST be applied to any proposed major production release of the software before its release, if there is at least one FLOSS tool that implements this criterion in the selected language. [static_analysis] 

A static code analysis tool examines the software code (as source code, intermediate code, or executable) without executing it with specific inputs. For purposes of this criterion, compiler warnings and "safe" language modes do not count as static code analysis tools (these typically avoid deep analysis because speed is vital). Some static analysis tools focus on detecting generic defects, others focus on finding specific kinds of defects (such as vulnerabilities), and some do a combination. Examples of such static code analysis tools include [cppcheck](http://cppcheck.sourceforge.net/) (C, C++), [clang static analyzer](https://clang-analyzer.llvm.org/) (C, C++), [SpotBugs](https://spotbugs.github.io/) (Java), [FindBugs](http://findbugs.sourceforge.net/) (Java) (including [FindSecurityBugs](https://h3xstream.github.io/find-sec-bugs/)), [PMD](https://pmd.github.io/) (Java), [Brakeman](https://brakemanscanner.org/) (Ruby on Rails), [lintr](https://cran.r-project.org/web/packages/lintr/index.html) (R), [goodpractice](https://cran.r-project.org/web/packages/goodpractice/index.html) (R), [Coverity Quality Analyzer](https://scan.coverity.com/), [SonarQube](https://www.sonarqube.org/), [Codacy](https://www.codacy.com/), and [HP Enterprise Fortify Static Code Analyzer](https://saas.hpe.com/en-us/software/sca). Larger lists of tools can be found in places such as the [Wikipedia list of tools for static code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis), [OWASP information on static code analysis](https://www.owasp.org/index.php/Static_Code_Analysis), [NIST list of source code security analyzers](https://samate.nist.gov/index.php/Source_Code_Security_Analyzers.html), and [Wheeler's list of static analysis tools](https://www.dwheeler.com/essays/static-analysis-tools.html). The [SWAMP](https://continuousassurance.org/) is a no-cost platform for assessing vulnerabilities in software using a variety of tools.

It is SUGGESTED that static source code analysis occur on every commit or at least daily.

See also https://github.com/confidential-containers/community/issues/2

**Comment by wainersm** [comment]
Related with static code analysis, I think we should enable a checker on pull requests to ensure new source files have the copyright notice on their headers as suggested by CNCF: https://github.com/cncf/foundation/blob/main/copyright-notices.md

For two occasions I saw that issue being discussed on pull requests for the operator:

- https://github.com/confidential-containers/operator/pull/114#issuecomment-1273338522 (Cc @fidencio)
- https://github.com/confidential-containers/operator/pull/79#discussion_r966679919 (Cc @bpradipt)
I looked at the image-rs, operator, attestation-agent repositories and none have such as checking for pull requests.

Maybe that is an example of "Applying standard processes and checks across the repos" that @jodh-intel has tried to bring up to discuss in our weekly meetings? 



@dcmiddle would you like to break it in another issue?

**Comment by jodh-intel** [comment]
@dcmiddle, @wainersm - This is a subset of https://github.com/confidential-containers/documentation/issues/35 which I'm hoping to get some airtime to discuss at the meeting on Wednesday.

The [Kata static checker](https://github.com/kata-containers/tests/blob/main/.ci/static-checks.sh) already handles checking of license headers (and an awful lot more besides ;)

**Comment by ariel-adam** [comment]
@dcmiddle is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by dcmiddle** [comment]
@ariel-adam this should stay open as we do not have good static checkers across CoCo yet.

@wainersm thanks for adding.. Fine to track licensing/copyright checks here. The main goal of this issue is doing security related static analysis. One could argue, that improperly licensed contributions create an availability risk. That should mostly be caught by DCO checks (signed-off-by). The spdx license banner checks may help with future sbom requirements.
Community Copyright labels IMO are not very consequential. I think they just help follow the provenance of the file as it is copied to other projects.

Besides, Kata static checker, are there other static checks we could inherit from Kata for code correctness / security?
I'd also like to see language linters everywhere.

**Comment by jodh-intel** [comment]
ftr, the Kata static checker checks the SPDX headers (with exclusions). We also have GitHub actions to check the validity of all commits (Signed-off-by, plus general commit formatting and fixes issue number, _etc_).

**Comment by mythi** [comment]
taking this one and added to the board

**Comment by mythi** [comment]
we can use CodeQL for the Go based projects and "N/A" for Rust (I did a quick cross check against other Rust project that have this requirement marked as completed and in all of those it was just "rustc/clippy/cargo audit".)

**Comment by mythi** [comment]
Status:

- [ ] https://github.com/confidential-containers/operator/pull/425
- [ ] cloud-api-adapter
- [ ] trustee-operator
